version = 0.1

[default.deploy.parameters]
stack_name = "leetcoach"
resolve_s3 = true
s3_prefix = "leetcoach"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
parameter_overrides = "AlertEmail=\"varun.anand2006@gmail.com\""

[default.global.parameters]
region = "us-east-1"
